### ISSUE TITLE
删除与编辑功能

### ISSUE THREAD

**Issue by plidezus** [plidezus/aimozhen#15]
在自己查看自己分享的视频的时候，希望能有删除功能和编辑功能。（图片少做了编辑按钮……囧rz）
![ - ](https://f.cloud.github.com/assets/379821/80409/1face228-6256-11e2-8022-2ae9786ac0cd.jpg)

**Comment by GavinFoo** [comment]
大体样子已经做完，编辑已经可以使用，删除已经单独开issue给拉哥了
