### ISSUE TITLE
首页样式调整

### ISSUE THREAD

**Issue by plidezus** [plidezus/aimozhen#18]
黑色块颜色太深并且无法展示完title，希望修改下样式。
- 将title向下挪至图片下面，并且只显示一行
- 内容显示2行，多余的..显示
- 首页图片上方增加视频数量统计
- 每个模块增加查看次数展示和收藏数量展示，颜色为#8c8c8c
- 每个模块的用户名和头像可以点击，点击之后跳转到用户页面
- 增加背景图（详见附件）
- 阴影颜色改为#E0E0E0
  ![ ](https://f.cloud.github.com/assets/379821/80436/f3af97c0-6259-11e2-80db-408ab9d4ed0b.jpg)
  ![bg](https://f.cloud.github.com/assets/379821/80438/ab1e2462-625a-11e2-8456-f4e515bec084.jpg)

**Comment by GavinFoo** [comment]
哇哈哈哈 全部完工！ fix  #18

**Comment by plidezus** [comment]
早上打开一看就一个惊喜，太帅了！好速度！中午我们俩会再调一把的！
