### ISSUE TITLE
播放详情页面UI调整

### ISSUE THREAD

**Issue by plidezus** [plidezus/aimozhen#20]
- Title字体18px
- 描述部分字间距22px
- “随便看看”改为“相关动画推荐”，最好图能大点，一行摆放4个即可~

**Comment by GavinFoo** [comment]
无觅 的图片最大为120PX 现在六个为107px 所以无法修改 其他问题均以修复 其中描述还增添了首字符缩进28px

**Comment by plidezus** [comment]
好的，那就不改了哈~
