### ISSUE TITLE
发布流程UI调整

### ISSUE THREAD

**Issue by plidezus** [plidezus/aimozhen#25]
- 第一步增加描述文字，详见附件（外框就用现在的即可，主要是文案和按钮布局）
- 第二步去掉左侧冗余的内容，更改提示文字和样式（标题18px，副标题12px，其他14px），右侧增加预览图。增加描述框的高度。去掉背景色。输入框宽度为首页的两个方块。
  ![ 2013-01-20 12 25 51](https://f.cloud.github.com/assets/379821/80859/d9086404-62ba-11e2-92c3-0b13f1597e8b.png)
  ![ ](https://f.cloud.github.com/assets/379821/80861/4ca465c0-62bb-11e2-94d3-b58e24ba82d2.jpg)

**Comment by plidezus** [comment]
我看第一步已经搞定了！好速度！

**Comment by GavinFoo** [comment]
快去试一试吧！输入描述和标题的时候会有惊喜的哟！哈哈

**Comment by plidezus** [comment]
我靠！太牛逼了！我都不敢奢望的效果也出来了！！！！！！！！！

**Comment by GavinFoo** [comment]
对了。登录，登出的提示方式也改了

**Comment by plidezus** [comment]
注意到了，我来调整下样式哈哈~
