### ISSUE TITLE
这里用来记录小bug

### ISSUE THREAD

**Issue by plidezus** [plidezus/aimozhen#26]
- 关注一个人之后按钮没有变，会让用户疑惑究竟关注成功没
- 登录之后的alert框内文字乱码
- 详情页面的描述之前不需要空2格
- 个人页面左侧的icon们都没有对齐
- 登录的时候“用户名”改为“邮箱” —— 话说我们现在不支持用户名登录吧？
- 右上角+号换为“分享动画”

————20120122新增————
- 详情页面的描述文字，支持换行吧。否则都堆到一起很难看。
- 全站文字改为#555
- line-height改为180%
- 去掉多说的喜欢，和收藏重复了。

**Comment by GavinFoo** [comment]
1、正在和拉哥做最后的处理
2、正在查找原因（成功提示正常、失败提示有问题）
3、已经去除
4、我使用Chrome和傲游以及IE尚未发现问题 给我截个图片吧
5、支持用户名登陆，你的用户名首字母为大写
6、已经更换

**Comment by plidezus** [comment]
辛苦啦！

**Comment by GavinFoo** [comment]
1、http://www.aimozhen.com/detail.php?id=116  已经改好了 
2、已经修复
3、已经修复
4、已经修复

**Comment by GavinFoo** [comment]
fix #26 -2
