### ISSUE TITLE
需要修改的小问题

### ISSUE THREAD

**Issue by plidezus** [plidezus/aimozhen#27]
这个case不要直接关掉哈。一些小东西都记录在这里好了。
- 评论是否还是用原生的？否则我登录之后还得再登录才能留言。（待议）
- 发布的时候提示文字为“支持优酷，土豆，ku6等视频网站。希望支持更多视频网站请点此（这个把用户带到反馈页面）
  艾墨镇的氛围和你息息相关，希望你能给我们带来更多精彩的分享”
- 首页12px的字体行间距150%，去掉.post-explain的margin吧？让首页的title和文字紧凑点？
- 文案修改“欢迎您来到艾墨镇，如果您是第一次来到这里，我建议您随意逛逛。如果您开始喜欢这里，那或许您更愿意住在这里。如果您已经在这里安家，欢迎您回来。” —— 修改为“欢迎你来到艾墨镇，这里居住着一群热爱独立影像的朋友们。你可以在这里尽享大家分享的精彩内容，留言讨论。当然更欢迎你的加入，和我们分享更多的精彩！”

**Comment by GavinFoo** [comment]
http://dev.duoshuo.com/threads/5023323ce9b7bde608000012 多说官方有一个多说SSO登录说明的文档 不知道拉哥能否整合

**Comment by plidezus** [comment]
我来问问

**Comment by fcrosfly** [comment]
可以整合，但是不想把这个东西帮在我们的系统上，因为除了SSO以外，我们拿不到其他实际的好处。我倒宁愿绑一个weibo账号

**Comment by plidezus** [comment]
我们自己的评论系统能用么？
我还是希望能用我们自己的评论系统。因为这个会比较有价值，初期还不指望能分享出来。
两位看呢？

**Comment by GavinFoo** [comment]
我觉得都是各有各的好处，但是如果现在不用的话，之后使用可能存在无法导入到多说之类的系统的问题

**Comment by GavinFoo** [comment]
文案已经修改 
首页12px的字体行间距150%，去掉.post-explain的margin吧？让首页的title和文字紧凑点？
这个模块要改的话是全站都修改的，所以要是改了首页的所有的页面都会被改掉

**Comment by plidezus** [comment]
那间距先不动哈
在 2013-1-26 下午11:04，"GavinFoo" notifications@github.com写道：
