### ISSUE TITLE
视频自动播放

### ISSUE THREAD

**Issue by GavinFoo** [plidezus/aimozhen#28]
视频自动播放

**Comment by plidezus** [comment]
怎么说？好了？
在 2013-1-21 下午11:50，"GavinFoo" notifications@github.com写道：

**Comment by GavinFoo** [comment]
http://player.youku.com/player.php/sid/{$id}/v.swf?VideoIDS={$id}&isAutoPlay=true

**Comment by GavinFoo** [comment]
http://www.tudou.com/l/{$matches[0]}/&resourceId=0_05_05_99&iid=141206757&autoPlay=true/v.swf

**Comment by GavinFoo** [comment]
http://player.56.com/renrenshare_$id.swf

**Comment by GavinFoo** [comment]
fix #28

**Comment by GavinFoo** [comment]
酷六网存在分享问题 @fcrosfly  @plidezus

**Comment by plidezus** [comment]
具体什么情况？
