### ISSUE TITLE
分类和Tag的规则

### ISSUE THREAD

**Issue by plidezus** [plidezus/aimozhen#29]
整理好了分类，一共十个，劳烦拉哥添加进数据库吧。
1、故事短片  
2、MV  
3、栏目包装
4、广告/宣传片
5、片头片尾
6、视觉特效
7、实验动画  
8、小创意 
9、预告片：
10、纪录片

另外，每个片子允许最多添加6个tag~ 多谢~

**Comment by plidezus** [comment]
好效率！

**Comment by plidezus** [comment]
那个 “动画”，能否改成“故事短片”

**Comment by plidezus** [comment]
拉哥，小傅问代码是哪样的？怎么加？

**Comment by fcrosfly** [comment]
aimozhen\ajax\edit_video.php 有个实例

可以用

``` php
Tag::getAllPreTags();
```

拿到所有预定义的Tag

**Comment by plidezus** [comment]
交给fuxiaopang了~

**Comment by plidezus** [comment]
记得别忘记videodetail页面右侧下方是tag的展示哦！

**Comment by GavinFoo** [comment]
这个根据每个作品调取作品如何实现？ @fcrosfly

**Comment by GavinFoo** [comment]
对了，还有一个就是如何获取这篇文章的主要tag和自定义tag

**Comment by GavinFoo** [comment]
fix #29
