### ISSUE TITLE
用户权限组

### ISSUE THREAD

**Issue by GavinFoo** [plidezus/aimozhen#35]
现在存在收藏和喜欢的功能，但是如果不能登陆的话这些功能就无法实现，所以我觉得需要分组分成内测制作者和订阅者，以实现满足和喜欢这两个功能

**Comment by plidezus** [comment]
收藏必须是注册用户才能用。

喜欢是多说的吧？能否去掉？

希望只给用户一个概念。不要拆组，之后管理起来很麻烦。没登录的用户点了收藏提示去登录就好。
在 2013-1-26 下午10:35，"GavinFoo" notifications@github.com写道：

**Comment by GavinFoo** [comment]
已经去掉喜欢了，但是现在的问题是如果注册了就能发视频，所以内测的时候不能参与的用户就不能收藏了

**Comment by plidezus** [comment]
是的哦。

我本来打算就是区分注册和非注册。

你意思是收藏这个功能对大多数用户来说都没法用了吧？

其实有考虑过任何人可以用微博登录，但是通过审核的才能分享。

但是考虑到实现太复杂，所以没提。内测我觉得还是简单点比较好。现在最需要的是删除和分类功能。这两个好了之后就能邀请人来测试了。

辛苦啦！
在 2013-1-26 下午11:40，"GavinFoo" notifications@github.com写道：

**Comment by GavinFoo** [comment]
已经调整
