### ISSUE TITLE
用户注册页面增加输入验证  并修复Email提交问题

### ISSUE THREAD

**Issue by GavinFoo** [plidezus/aimozhen#39]
用户注册页面增加输入验证  并修复Email提交问题
![ 20130203032221](https://f.cloud.github.com/assets/3000737/121099/6a790354-6d6e-11e2-9776-adb17185963b.png)

**Comment by GavinFoo** [comment]
fix #39

**Comment by GavinFoo** [comment]
@plidezus  由于之前表单提交问题所以现在需要人工输入如下用户的Email地址
tea86
Andrew Lee
小简
宝猫叫
老然
vclwei

**Comment by plidezus** [comment]
tea86@animetaste.net
dongzhen.li@gmail.com
xiaojian@animetaste.net
602771446@qq.com
furan-1126@qq.com
li.wei.vc@gmail.com

**Comment by GavinFoo** [comment]
已经修复完成
