### ISSUE TITLE
20130218 反馈的bug们

### ISSUE THREAD

**Issue by plidezus** [plidezus/aimozhen#41]
功能方面
- 点击用户出来的菜单改为鼠标hover之后出来，并增加邀请的选项入口
- login之后去掉左侧“11位镇民，228部视频”这段话。
- 在某个分类下，点击第二页的url是“http://aimozhen.com/tag/?id=2?p=1” ，而第三页就是“http://aimozhen.com/tag/?id=2?p=1?p=2”
- 页码没有当前选中的状态。
- tags还不能点击。之后tag你有啥想法？是否在header增加一个入口，让用户能看到所有的tag？
- 先去掉热榜，等拉哥修改好了逻辑之后再加上如何？现在万年不变。
- 检查一下多说，我在mac下的chrome上死活无法用weibo auth进来
- 自己的页面没有翻页“http://aimozhen.com/user.php?id=3”
- 把“未分类”的名字改为“归类无能”吧，这样就不用再手动的分“归类无能”
- 所有的弹出提示能否和分享视频的样式统一？（如果需要设计给我说下）
- 发布时候url出错现在会报错“Fatal error”，能否给一个前端url规则检查，或者给一个什么提示？

视觉方面
- 放“艾墨镇共有 228 部视频作品与您分享”的区域的背景高度为50px
- logo年后会给出来哈哈。

还有就是新用户如何申请内测？是否把左边的大红色按钮改为“申请内测”，然后用一段QQmail的代码http://mail.qq.com/cgi-bin/qm_share?t=qm_mailme&email=waCvqKyktaCytaSBsLDvoq6s 这样来通过邮件申请？

另外说说分类和tag功能，
我是想左侧的方块中放当前分类下的tag，然后在顶部放一个分类链接，点击之后下拉菜单让用户选择看什么分类。

最后说一句！辛苦啦！

**Comment by GavinFoo** [comment]
logo已经做了个临时的，你多按几下F5 看一下
其他的问题我等看一下

**Comment by plidezus** [comment]
logo太贴心了！赞！org的也加上了哈哈！

**Comment by GavinFoo** [comment]
弹出提示 只能修改该配色和配图，这个你可以做一下，我修改一下

**Comment by GavinFoo** [comment]
修改进度 80%

**Comment by GavinFoo** [comment]
视频验证已经上线 现在提供 优酷土豆56的检验，其他的地址分享还是有获取的问题，我之后再做实验

**Comment by GavinFoo** [comment]
用户分页也没有问题了

**Comment by GavinFoo** [comment]
你再看一下还有什么需要修改的

**Comment by GavinFoo** [comment]
All Fixed #41
