### ISSUE TITLE
View类和Page类

### ISSUE THREAD

**Issue by fcrosfly** [plidezus/aimozhen#49]
现在的HTML越来越多了，需要重构一下代码，不如后续开发不好进行了。

**Comment by plidezus** [comment]
辛苦了，有时间点么？
在 2013-2-18 上午11:18，"fcrosfly" notifications@github.com写道：

**Comment by iwege** [comment]
为什么不直接使用开源框架去做呢？可以节省很多的编码时间。

**Comment by penkzhou** [comment]
有这样类似的框架么？

**Comment by fcrosfly** [comment]
有很多啊，随便找个MVC框架都不错

2013/5/27 Penk Zhou notifications@github.com
