### ISSUE TITLE
在Detail页面增加面包屑

### ISSUE THREAD

**Issue by plidezus** [plidezus/aimozhen#5]
在Detail页面增加面包屑

**Comment by plidezus** [comment]
这个想清楚了。规则是

home > 分类 > 片子title
这样在每个detai上加了之后，就可以取消打开新页面了。
因为现在每个片子都自动播放，如果同时开太多页面体验不好。

PS，说下这个自动播放，之前youtube的投资人说为什么youtube比别的视频网站好，原因自动播放是很重要的一个因素。

**Comment by GavinFoo** [comment]
fix #5
