### ISSUE TITLE
20130218 反馈的bug们

### ISSUE THREAD

**Issue by plidezus** [plidezus/aimozhen#52]
- 没有登录的时候无法浏览单个用户的列表
- 微博分享的时候，影片title会出现两遍。能否改为“我在@艾墨镇 看到一部不错的动画：{片名}，{描述} {URL} ”
- 邀请好友的界面，直接敲回车会关闭这个窗口
- 邀请好友界面，输入email之后出来url，点击下面的那个复制链接的按钮，本界面没有关闭，并且我更换输入email，无法生成新的url，必须刷新页面
- 删除/登录/退出的界面和分享的界面不统一，希望一致
- 网站的title改为“艾墨镇，分享视频，创造梦想”
- 每个分类页面的title为“{分类名} | 艾墨镇”
- 每个人的页面title为“{用户名} | 艾墨镇”

**Comment by plidezus** [comment]
这个都改完了吧？

**Comment by GavinFoo** [comment]
还差一个样式的修

**Comment by GavinFoo** [comment]
删除样式已经更新~
