### ISSUE TITLE
网站结构调整

### ISSUE THREAD

**Issue by plidezus** [plidezus/aimozhen#53]
![ ](https://f.cloud.github.com/assets/379821/201380/3316eaca-80f1-11e2-9feb-cff347c201a6.jpg)

目前首页是最新发布的，然后可以根据分类来查看最新的内容。还有另一个纬度是查看pv最多的。这样查找的纬度比较单一，不方便以后数据多的时候用户浏览，所以想调整下网站结构

调整后的结构

首页
- 最新
- 最热
- 我的关注（日后再说）
- 认证用户（日后再说）
- 分类（下拉菜单，就是现在的这些）

每日精选
- 以每天为单位，放今天浏览热门的片子。现在是记录的历史数据，几乎不会变化。对于老用户来讲看一两次就没用了。

其他调整：
- 单元模块的调整，查看评论样式和位置调整（这里的简介css还是和内页的分开，现在的间距太大了）
- header的位置调整，注意看设计稿的垂直对齐位置。现在头部的按钮等位置都没有和下面的模块对齐。
- 右侧只要有个视频总数就行了，也可以做成随机一句话哈哈
- 已经登录的用户不需要看到注册链接了

**Comment by fcrosfly** [comment]
嗯，没啥问题

**Comment by fcrosfly** [comment]
话说，放映厅（日后再说） 这个是啥？

**Comment by GavinFoo** [comment]
不错的说

**Comment by plidezus** [comment]
就是用户可以按照自己的需要创建一个列表

**Comment by GavinFoo** [comment]
fix #53

**Comment by plidezus** [comment]
还有几个小问题哈。
- 【重要】原创标签下的翻页是hot的翻页？
- 分割线是灰色和白色两根
- 次级导航的字体是选中的加粗黑色，没有选中的是灰色不是蓝色
- 次级导航文字挨的太紧，hover在分类上面就没法看了。
- 进入艾墨镇默认在发现这个标签上
- 有了最新，分类里面的“全部”就可以去掉了
- 最新tab下左上角第一个模块也可以去掉了（先注释掉吧）
- 次级tab和header的距离太高了，大概50px就好了

**Comment by GavinFoo** [comment]
缓存问题。。。。

发自我的 iPhone

在 2013-3-7，8:42，"LiuShaonan" notifications@github.com 写道：

**Comment by plidezus** [comment]
还有一堆小细节，你空了看下？起来的好早~

**Comment by plidezus** [comment]
恩，标签已经好了。

**Comment by GavinFoo** [comment]
狂按F5

发自我的 iPhone

在 2013-3-7，8:42，"LiuShaonan" notifications@github.com 写道：

**Comment by GavinFoo** [comment]
除了 次级tab和header的距离太高了，大概50px就好了 都改好了
我这边看正常，不知道你那边还有米有显示错误

**Comment by plidezus** [comment]
正常了！就是首页直接跳到最新吧？现在首页有点尴尬
—

**Comment by plidezus** [comment]
另外你去git上看下刚才更新了几条别的需要你的建议
—

**Comment by GavinFoo** [comment]
所以说首页是发现还是最新呢？

**Comment by plidezus** [comment]
是发现这个标签。发现这个标签默认为最新
在 2013-3-7 上午9:28，"GavinFoo" notifications@github.com写道：

**Comment by GavinFoo** [comment]
OK了
