### ISSUE TITLE
增加一种认证用户

### ISSUE THREAD

**Issue by plidezus** [plidezus/aimozhen#58]
想增加一种认证用户的类型。这些人将来可以作为一个特殊分类加到首页。这个之前的case提到过的。

这样可以更好的利用At和导演的关系来扩充片库，虽然导演不会经常来发，但是可以增加网站的权威性，还能让宣传有噱头。方便利用他们的资源推广。

拉哥看呢？实现有啥思路？

**Comment by fcrosfly** [comment]
可以啊，增加一个用户group就好了。

**Comment by plidezus** [comment]
那你跟@GavinFoo 同学谁来做？

**Comment by GavinFoo** [comment]
哇哈哈哈！终于完成咯！
fix #58

**Comment by plidezus** [comment]
霸气！效率！赞
在 2013-3-5 下午11:19，"GavinFoo" notifications@github.com写道：
