### ISSUE TITLE
【体验改进】右上角的登录按钮修改

### ISSUE THREAD

**Issue by plidezus** [plidezus/aimozhen#59]
现在右上角默认是登录，带来两个问题：
- 新用户过来之后不知道这是一个可以分享的社区
- 想注册的用户必须到首页左侧的模块才能看到

希望改为：
- 右上角固定为分享视频，如果是未登录用户，点击还是弹出登录界面
- 在头部增加申请内测和登录的入口，详见附件

PS：那个问题反馈改为“反馈”就好了。
![ -3](https://f.cloud.github.com/assets/379821/183730/980659c8-7cb1-11e2-8382-59b5fe896d94.jpg)

**Comment by GavinFoo** [comment]
左边完成

**Comment by GavinFoo** [comment]
右侧的明天弄一下

**Comment by plidezus** [comment]
辛苦啦，早点休息

2013/2/22 GavinFoo notifications@github.com

> 右侧的明天弄一下
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/plidezus/aimozhen/issues/59#issuecomment-13949220.

## 

刘少楠   Plidezus Leo

重要的不是你所得到的，而是你所付出的；重要的不是你的成功，而是你的价值；重要的不是你所学的，而是你所传授的；重要的不是你的能力，而是你的性格；重要的不是你认识多少人，而是你离开时，有多少人感到这是永久的损失。

Cofounder @ AnimeTaste.net
Gtalk: plidezus@gmail.com
Blog： http://www.plidezus.net

**Comment by GavinFoo** [comment]
Fix #59
