### ISSUE TITLE
收藏之后的按钮没有变化

### ISSUE THREAD

**Issue by plidezus** [plidezus/aimozhen#6]
应该reload页面并且显示按钮为“取消收藏”

**Comment by fcrosfly** [comment]
现在可以用

``` php
Action::isFav($user, $video)
```

判断一个User 是不是已经Fav了一个Video

**Comment by GavinFoo** [comment]
@fcrosfly  现在action声明中貌似有些问题，验证的$user 貌似是发布用户的id 而不是visitor的id。但是我把函数中的变量改为 visitor后，出现了永久变成1的情况 http://www.aimozhen.com/detail.php?id=95  “收藏回馈数值（TEST） 1”

**Comment by GavinFoo** [comment]
@fcrosfly 现在action声明中貌似有些问题，验证的$user 貌似是发布用户的id 而不是visitor的id。但是我把函数中的变量改为 visitor后，出现了永久变成1的情况 http://www.aimozhen.com/detail.php?id=95 “收藏回馈数值（TEST） 1”

**Comment by GavinFoo** [comment]
#6 -2
