### ISSUE TITLE
新用户申请

### ISSUE THREAD

**Issue by plidezus** [plidezus/aimozhen#66]
刚发现新用户申请用qqmail那个邮箱功能的时候必须登录才行。如果没有qq帐号就囧了。有什么能快速收集用户这些内容的工具么？能让用户点击输入内容之后就发邮件给我们的？

**Comment by GavinFoo** [comment]
这个需要搭建邮件系统。不如再留一个邮箱，想注册的如果没有QQ，在通过自己的邮件发送

**Comment by plidezus** [comment]
这个好，加上吧admin@aimozhen.com
在 2013-3-7 上午9:26，"GavinFoo" notifications@github.com写道：

**Comment by GavinFoo** [comment]
这个也OK了

**Comment by plidezus** [comment]
效率！
