### ISSUE TITLE
内测申请邮件做个前端检查，邮箱格式不对的不让其提交表单

### ISSUE THREAD

**Issue by plidezus** [plidezus/aimozhen#70]
否则我们就会被spam死哈哈~

**Comment by GavinFoo** [comment]
好的。我也发现了~

发自我的 iPhone

在 2013-3-20，17:37，"LiuShaonan" notifications@github.com 写道：

**Comment by GavinFoo** [comment]
Fix

**Comment by plidezus** [comment]
神速度
在 2013-3-22 下午2:28，"GavinFoo" notifications@github.com写道：
