### ISSUE TITLE
终于找到缩略图的问题了

### ISSUE THREAD

**Issue by plidezus** [plidezus/aimozhen#71]
目前缩略图很大，但是因为平铺导致首页图片粗糙而且显示不全。
但是考虑到优酷有的有黑边和logo，所以不能完全缩小，你看看调整到多少合适？

我是retina的屏幕所以没法计算。

用background-size 这个属性就好，支持百分比或者像素。

**Comment by GavinFoo** [comment]
这个我算的是16:9的视频刚刚好的值
再小一点儿就黑边了。除非我们把缩略图改成长方形

发自我的 iPhone

在 2013-3-20，17:49，"LiuShaonan" notifications@github.com 写道：

**Comment by GavinFoo** [comment]
不过长方形可能会不太好看

发自我的 iPhone

在 2013-3-20，17:49，"LiuShaonan" notifications@github.com 写道：

**Comment by plidezus** [comment]
改成16比9看看？来截图下？
在 2013-3-21 上午1:18，"GavinFoo" notifications@github.com写道：
