### ISSUE TITLE
个人页面修改

### ISSUE THREAD

**Issue by plidezus** [plidezus/aimozhen#74]
![faxian_MarkMan](https://f.cloud.github.com/assets/379821/280172/ddf58212-914a-11e2-8d50-f3490a61b40d.jpg)
详情请看图片。

另外个人用户这个模块修改之后记得所有动画页面右侧的用户模块一起修改掉哈~

**Comment by plidezus** [comment]
这个优先级不高，先放放。

**Comment by GavinFoo** [comment]
作废
