### ISSUE TITLE
重复分享的视频会重复出现

### ISSUE THREAD

**Issue by plidezus** [plidezus/aimozhen#9]
希望如果大家集中分享一个内容的时候，不会被刷屏。

实现方法有空讨论下。

**Comment by plidezus** [comment]
先处理成：
- 如果用户分享同一个url的视频，则将除第一个人之外的其他分享者带到这个页面的评论框位置即可。

**Comment by fcrosfly** [comment]
我会存一个VideoId，先顶一下。
